### ISSUE TITLE
Thebes weapons proc's are not the correct data type

### ISSUE THREAD

**Issue by bradbeam** [l1j/en#220]
Doing -dmg on when testing thebes weapons, they deal floating point damage ( 101.11220022332 ). We probably need to clean this up.

**Comment by Allthingsrelated** [comment]
Just posted a fix for this in addition to allowing the thebes proc to actually finish a mob off instead of leaving it at 1 hp and doing 0 dmg.

**Comment by smith-j-travis** [comment]
Closed in #385
