### ISSUE TITLE
Counter magic should block illusionist stun?

### ISSUE THREAD

**Issue by bm3719** [l1j/en#262]
A player reported that counter magic doesn't block ill stun, but should.  Need confirmation.

**Comment by Soren8** [comment]
I don't know how this worked on live but I think this makes sense, since AFAIK (which isn't much about illusionists), their spells have no chance to miss, so should be affected by CM.

**Comment by Soren8** [comment]
I say we leave it alone, as this may have been another private server's customization they're remembering. It's still operates like this in upstream.

**Comment by bm3719** [comment]
Agreed, absent any verification to the contrary.  Closing.
