### ISSUE TITLE
Implement Cockatrice, Scarecrow, and Yeti dolls

### ISSUE THREAD

**Issue by bm3719** [l1j/en#265]
Turns out the sprites for these exist, so it should be no problem enabling them.

This will need:
- List of doll effects.
- npc and etcitem table entries.
- A way to get them (current plan is to just have them as super-rare Arka bag rewards, though that's an imperfect and temporary solution).
- Middle tier support code that implements the doll actions.

**Comment by Zylaxyma** [comment]
Cockatrice and Yeti dolls have been added in merge by Brad Beam #322 and #324. Scarecrow doll itself is working, but the inventory graphics for this item is not available using either our current connector or client
