### ISSUE TITLE
Insight effect remains after timeout

### ISSUE THREAD

**Issue by bm3719** [l1j/en#268]
The icon goes away after 300 sec, but the +1 stat bonus remains until restart.

**Comment by bm3719** [comment]
Confirmed this works fine on my local server, but also confirmed the bug exists on zelgo.  Must be a problem in just the zelgo branch.

**Comment by Soren8** [comment]
I think this is due to db/optional/illusionist_tweaks.sql. Insight duration is set to 1200, but the icon duration may be statically set client side.
