### ISSUE TITLE
Baphomet and Beleth don't summon monsters

### ISSUE THREAD

**Issue by Soren8** [l1j/en#270]
Baphomet should summon skeletons and Beleth should summon cerberuses, but neither do.

**Comment by Zylaxyma** [comment]
Working on this feature, limited web resources to verify if Baphomet summons skeletons or Spartoi, or a mix of skeleton types. Unable to determine full complement of summons for Beleth. More research needed

**Comment by Zylaxyma** [comment]
Thank you, I'll generate the content we're missing from the details provided
