### ISSUE TITLE
IQ staff NPC not showing dialog option

### ISSUE THREAD

**Issue by bm3719** [l1j/en#273]
Players report that the NPC in MLC 6F that makes IQ staff doesn't have the option for it anymore.  He only makes Beleth/Bapho/Demon staff now.

Needs some research.

**Comment by SoundWave6666** [comment]
The Npc to make iq staff should be in a hut in giran south west of the dwarves

**Comment by bm3719** [comment]
Right you are.  Thanks much for the info.
