### ISSUE TITLE
Kill/stat boards

### ISSUE THREAD

**Issue by tricid** [l1j/en#279]
At one time I had a board in oren showing a top 10 list for kills, class based levels, and over all levels (not sure if there was anything else).  imo these should be reimplemented.  

I think the code that collects the data for kills is still there, along with the table.  It's just not being used or displayed anywhere.  

Maybe make all of it configurable in the process

**Comment by mikesa83** [comment]
I think putting this on the website might make more sense/be more consumable than in-game no?

**Comment by tricid** [comment]
finally found (and fixed) my old code for this, should be committing this weekend.

I might skip making it configurable.  It's tied to a board with a specific ID, so anyone that doesn't want it can just despawn that board in the DB.  Or I can put the SQL to make it spawn in an optional sql file in db/.  one way or the other, that's configurable enough for me lol

**Comment by smith-j-travis** [comment]
#483 closes this
