### ISSUE TITLE
Elves can't shoot long range after dieing

### ISSUE THREAD

**Issue by Recenven** [l1j/en#282]
EDIT: Only when you die this happens teleporting still allows you to shoot long range its when you die.

was doing level 30 elf quest whenever i died i could not shoot long range any longer i would have to be right within melee distance to attack the mob with my bow only workaround i had is to relog it fixes it but as soon as i die he issue comes back

On S3EP1

**Comment by Recenven** [comment]
I may have fixed it tried multiple times after applying this.. seems that the bug has gone away.

pc.startObjectAutoUpdate();
add above after
pc.startMpRegeneration();
and recompile and seems that this issue is gone.

**Comment by Soren8** [comment]
Alt-key probably stuck down. Alt causes you to walk towards monsters instead of attacking from long range. Hit the alt key one more time when you tab back in, so the "key up" event is triggered.
