### ISSUE TITLE
.item itemid fix to scale with your rate in config file

### ISSUE THREAD

**Issue by Recenven** [l1j/en#283]
In my opinion this is an enhancement the old way doesn't scale with your config rate as with this change it does.

Change:
chance[i]=rs.getInt("chance")/(double)10000;

To:
chance[i]=rs.getInt("chance")/(double)10000 * Config.RATE_DROP_ITEMS;

this is in server.server.command.executor.L1ItemDrops

**Comment by Soren8** [comment]
Please open a pull request for this if you want it
