### ISSUE TITLE
Actionbars (F5 through F12) do not save sometimes

### ISSUE THREAD

**Issue by Recenven** [l1j/en#287]
Sometimes if you get d/c or simply log into another character and log back on to the same one, your actionbars will not save the recently put icons on there and revert back to the previous ones. Is there a way to change the save interval of this?

**Comment by Soren8** [comment]
Those only get saved when the client uploads the config to the server. So we're limited by the client's actions here.

**Comment by Recenven** [comment]
Where is this located at?

**Comment by Recenven** [comment]
Fixed on my fork tested and no issues on my end #287 closed
