### ISSUE TITLE
Castle ownership transfer not teleporting offline players characters

### ISSUE THREAD

**Issue by L1predev** [l1j/en#330]
If this is somewhere addressed, please let me know.

Once the castle changes ownership during a siege, all online players are teleported out of the castle. Offline players however can log in to the castle with ownership having been changed. They can then PK, open doors etc.

javolution-5.5.1

Safe zone is a temporary fix.

I'm new to this, please be gentle.

Thank you.

**Comment by smith-j-travis** [comment]
When ownership changes, should everyone get teleported to town, or just those who try to login?

For example: 
Player A is offline in the warzone and the siege is going on. They login and are not in the owning clan, so they get teleported to the appropriate town.

Player B was offline in the warzone when the castle changed owners. They did not login during the siege time, so when they login after the siege has ended, should they be in the town as well, or should their coordinates be maintained?

**Comment by L1predev** [comment]
Good Evening Travis,

Thank you for the response.

Both your scenarios are correct, no matter what the player not owning the
castle should be teleported to say Giran X (warp 3)

Currently when a player logs in, especially after the siege and they do not
own the castle, they remain within the castle, even in the throne zone
where the storage dwarf is, this should not be the case.

I'm attempting a work around by turning the whole zone to send the player
to Giran X (warp 3) upon log out, I'm looking into doing this and I think
it's in the database settings. Sure this affects players that own the
castle, but since no einhasad points are awarded there due to it not being
a safety zone it's kind of doing them a favour :)

**Comment by smith-j-travis** [comment]
Well right now everyone (even GMs) get teleported when the siege starts, so I'm trying to find the code that handles that. I, for some reason, that code is client-side, it shouldn't be hard to teleport players out of the castle (even offline) through code instead of doing a logout hack.

As for your hack, before you spend any time on it, you might want to relay it to those would can commit code, as they might not like the solution and your fix may be in vain.

**Comment by smith-j-travis** [comment]
Scratch that last post. If you login during a siege it teleports you to town, but the siege start does not automatically teleport the player to town.

**Comment by smith-j-travis** [comment]
This has been fixed as of pull request #335
