### ISSUE TITLE
items with level requirement stuck

### ISSUE THREAD

**Issue by tricid** [l1j/en#332]
from forum post

" If you equip items that have a level requirement and then die and de lvl you can't take them off."

**Comment by smith-j-travis** [comment]
How did this work on live? It seems the easiest way to handle this would be to unequip the items on de-level. 

Did it

a) Unequip them on de-level
or
b) Allow you to unequip them manually
?

**Comment by smith-j-travis** [comment]
I went with allowing the user to unequip. I think that is how it worked on live.

**Comment by tricid** [comment]
Closed by https://github.com/l1j/en/commit/e4c74ace99cd0b46fa269f938e86c4c70b157de2
