### ISSUE TITLE
Drop rate of tarak item needs buff

### ISSUE THREAD

**Issue by Kutegirl** [l1j/en#347]
0.03 for his robe, boots, gloves, and cloak are too low. Here's reasonable suggested drop rate from live server. They have hunted 1k tarak to get the result. Please scroll down to see the results. 

http://lineage.power.plaync.com/wiki/%ED%83%80%EB%9D%BD+%EB%93%9C%EB%A1%AD+%EC%95%84%EC%9D%B4%ED%85%9C+%ED%99%95%EB%A5%A0+-+2010%EB%85%84+7%EC%9B%94+22%EC%9D%BC

**Comment by antonio-marino** [comment]
This is probably the reason: https://zelgo.net/linweb/topic/read/328

**Comment by tricid** [comment]
Closed by 19bbf5e384ea12fbd89cf293d2e38eaa0e144d48
