### ISSUE TITLE
Thunder Grab is Broken 

### ISSUE THREAD

**Issue by Kutegirl** [l1j/en#350]
Thunder grab (Dragon knight skill) doesn't hold the target.  It should hold the target for 1~4 seconds by chance.  We tried it numerous times, but none worked.  Please take a look at it.
-KG

**Comment by Hush1982** [comment]
The skill is not broken.  Its success rate is dependent on INT.  More help on DK abilities can be found in the help menu provided in the client.

**Comment by smith-j-travis** [comment]
Is this fixed by #386?
