### ISSUE TITLE
Drake Quest

### ISSUE THREAD

**Issue by antonio-marino** [l1j/en#353]
According to a player on ress (SoundWave), there is a part of the quest that is bugged. There is a npc that is supposed to polish your ring, but that option is never given.

http://noobs-are-us.blogspot.com.br/2011/02/pirate-island-drake-quest.html

**Comment by pbeentje** [comment]
Player failed to complete the side quest required for the next step and was later successful after completing the quest.
I can replicate this and the above site confirms this is correct behavior for live.

**Comment by smith-j-travis** [comment]
Closing this since it seems to not be an issue.
