### ISSUE TITLE
Cougar should required 44CHA

### ISSUE THREAD

**Issue by smith-j-travis** [l1j/en#369]
Based on the post here:

https://www.zelgo.net/linweb/topic/read/701

>Official (live) and the "wiki" players always uses.
>Some info about this "wiki":
>Its run by an individual or group (not too sure) that updates L1's info since the beginning, later the webpage collaborated with a gaming magazine publisher website to form this "wiki".
>The information was kept updated routinely by players and sources like Kr, Jp, GMs etc. (On the side note, it almost didn't have any errors before. Even if it somehow happened, it was corrected extremely quickly.)
> 
>Source One: Official (http://tw.beanfun.com/Lineage/main.aspx)
>It was not easy as official don't really publicize anything that you can find in game or game data.
>Link to the source:
>http://tw.beanfun.com/lineage/events/20120926_icelair/page3.html
>Direct link to picture of interest:
>http://tw.beanfun.com/lineage/events/20120926_icelair/images/UI/08.jpg
>Luckily the game update screenshot captures the Cougar which is at Lv.72 [44/1]
 
>Source Two: "Wiki" (http://gametsg.techbang.com/lineage/index.php)
>Summon skill description page:
>http://gametsg.techbang.com/lineage/index.php?view=skill&skill=190
>Charisma info page:
>http://gametsg.techbang.com/lineage/index.php?view=article&articleid=1163447
> 
>Source Three: Official (http://lineage.plaync.com/)
>Source:
>http://lineage.power.plaync.com/wiki/CHA
>쿠거
>레벨 72, CHA 44 이상
>Translated : Cougar Level 72, CHA 44 or more

It has links to a few websites that seem to reinforce that cougar should require 44 charisma to summon.

**Comment by PyroAmos** [comment]
yes, it should be 44 cha (well, 50 cha including the 6 hidden cha for mage). LinLib was accurate (at least to summon requirements) at time of live

Mage: Summon Requirements 
Required Level Type of Summons Number of Summons Summon Limit 
up to       52      various                   (CHA+6) / 8                 none 
          56-59      various                   (CHA+6) / 10               none 
          60-63      various                   (CHA+6) / 12               none 
               64      Hell Bound             (CHA+6) / 20               none 
               68      Doppleganger        (CHA+6) / 30               1 
               72      Greater Minotaur   (CHA+6) / 30                1 
               72      Cougar                   (CHA+6) / 50               1

**Comment by PyroAmos** [comment]
Side note, linlib has pet cha requirements were different to, jindo puppy & tiger are supposed to be cha(+hidden cha)/12. no one on live tamed them, but they pulled those numbers strait from the GM (either that or they translated them), since no one on live tamed either of them (to my knowledge anyway) I can't really say one way or the other if that was accurate to live.
