### ISSUE TITLE
Screen Lag

### ISSUE THREAD

**Issue by GraphicDrumms** [l1j/en#382]
Hello, I just started playing and my screen is lagging, it isn't refreshing. First my bottom screen wasn't working so I couldn't tell if I was  using pots or my hp/mp/exp bar wasn't moving. Now only my top screen isn't refreshing. Please help, I miss this game.

**Comment by smith-j-travis** [comment]
What operating system are you using? Have you tried updating your graphic card drivers?

**Comment by GraphicDrumms** [comment]
I am using a Windows 7 64-bit os, no I have not.

**Comment by smith-j-travis** [comment]
And are you using the exact client located at: https://www.zelgo.net/linweb/static/files/LineageTikal.zip?
If you are, I would suggest trying to update your graphics card drivers.

**Comment by GraphicDrumms** [comment]
Yes and I just updated my graphic driver. Still no good :/. It works every now and then where I can play for a while, but then the screen starts to freeze.

**Comment by smith-j-travis** [comment]
I'm going to close this as it isn't an issue with the server code. It might help to ask some people at https://zelgo.net to see if anyone has a solution to your issue.
