### ISSUE TITLE
Base Stat bonus not given on char creation 

### ISSUE THREAD

**Issue by PyroAmos** [l1j/en#388]
Base Stat bonus is not being given on char creation... they are given when you use candle and restat however.

**Comment by smith-j-travis** [comment]
Could someone give me more detail on this? Like an example I could test to see if I can reproduce? I'm not really sure what the stats should be.

**Comment by PyroAmos** [comment]
was discovered when mages candled they would get more hp/mp with same stats (18con/wis) since start stat bonus enabled when they candled. I asked if the +4hit/dmg from base 20str knight didn't enable unless you candled and no one could give me a straight answer, so since I hadn't candled (and I was 20str knight), I did dmg test unbuffed, candled to same stats (20str base) and did dmg test again the max/min dmg rolls went up 4.
