### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Cronicman** [l1j/en#432]
cannot play lineage on windows 10, login.exe will not load up to the screen at all.

**Comment by smith-j-travis** [comment]
Which connector and bin file are you using? This is really the place to post about L1J issues and glitches, not the client itself.... Zelgo.net would be a better place to post client issues.

**Comment by Cronicman** [comment]
s3ep1 login_v240

**Comment by smith-j-travis** [comment]
Yeah that won't work. You will either have to use a virtual machine on Windows 10, or you can use the launcher I created that is available in my repos.

**Comment by Cronicman** [comment]
I used your launcher changed IP and stuff & compiled but it gets to the login screen that says that s3ep1 bin stopped working.

**Comment by smith-j-travis** [comment]
It should have prompted you to use the S3EP1U.bin file instead of S3EP1.bin. If not, do a check files and go into your settings. Under the client bin file there should be an option for S3EP1U.bin.

If you select that it should run.

**Comment by Cronicman** [comment]
it runs but when i get to the login screen it says it stops working.

**Comment by smith-j-travis** [comment]
Try it a couple times. The S3EP1U.bin file can be wonky, but once you actually get past the login screen it seems to be rock solid.

Also, some users reported an issue if they play in windowed mode and move the window before it has finished loading. Try not moving the window until you've logged in.

**Comment by Cronicman** [comment]
Before I do that should i delete s3ep1 & s3ep1u and let the launcher redownload them?

**Comment by smith-j-travis** [comment]
nope. If you have S3EP1U.bin you should be good to go.

**Comment by Cronicman** [comment]
tried it 6 times & more it still doesn't want to work. this is what i edited in the launcher also i compiled it for release - x86 should it try a different?
                "Lands of Aden", 
                new Server
                {
                    Ip = "192.168.1.5",
                    Port = 2000
                }

**Comment by Cronicman** [comment]
yes thats my lan ip, im trying to get my bro to be able to lan play with us.

**Comment by smith-j-travis** [comment]
That should all work. You're sure you selected S3EP1U.bin in settings and not S3EP1.bin? I've never heard of it not working for anyone on Windows 10...

**Comment by Cronicman** [comment]
I'm 100% positive i've selected S3Ep1U.bin, I load it up get past the ncsoft screens to the login screen and it pops up S3EP1U.bin has stopped working. I also selected my server obviously from the list.

**Comment by smith-j-travis** [comment]
Sorry, not sure what you can do then. At this point you'll probably have to have your friend on Windows 10 load up a virtual machine

**Comment by SoundWave6666** [comment]
Have you tried running it in compatibility mode for Windows XP?

**Comment by Cronicman** [comment]
^ yes still nothing.

**Comment by Cronicman** [comment]
new error on fullscreen mode: resoulution change failed! failed to modify resoulituon

**Comment by smith-j-travis** [comment]
Another random question, but have you tried it in both windowed and non-windowed mode?

**Comment by Cronicman** [comment]
hmm i dont have LinS3EP1.dll should I have this?

**Comment by smith-j-travis** [comment]
Nope, you don't need it.

**Comment by Cronicman** [comment]
I'm gonna download the Client on L1J resurrection site then cause i got some client that must be old or outdated.

**Comment by Cronicman** [comment]
Also how do you stop the updater from overriding the text pak/idx files cause i have my own customized text pak/idx files I use and don't want that to override it?

**Comment by smith-j-travis** [comment]
You will have to point it to another server than mine. The current build connects to my server and downloads files specific to resurrection.

If you point it to a non-existant server it will also stop all downloads.

**Comment by Cronicman** [comment]
which i did
"Lands of Aden", 
new Server
{
Ip = "192.168.1.5",
Port = 2000
}
so i should be fine then? Thanks! I'll let you know when the client gets done downloading if it works.

**Comment by smith-j-travis** [comment]
No, that is the server info for the game. The updater has something pointing to travis-Smith.ca. 

Also if you are trying to use a newer client than resurrection uses, then the client is completely untested.

**Comment by Cronicman** [comment]
No im downloading resurrections client from the website, just gonna replace the launcher with the new one i compiled. Thanks for that info.
