### ISSUE TITLE
Add bloodpledge to kill announce

### ISSUE THREAD

**Issue by tricid** [l1j/en#453]
I think the blood pledge name needs to be included in the kill messages.  Such as

Bob [PRESIDENTS] killed Blah[KINGS] in battle.

**Comment by smith-j-travis** [comment]
Are we going to store that in the DB as well? Would be handy to show what pledge has the most overall kills/stats as well.

**Comment by smith-j-travis** [comment]
Whoops. This was closed by #461 
Should probably create a new issue for storing bp kills in the DB.

**Comment by tricid** [comment]
not sure if I even want to really.  A query can pull that from player data, it'd just change as players join/leave a pledge (not sure if that is a good or bad thing yet, that'll be the decision maker).
