### ISSUE TITLE
boss kill logging (to DB)

### ISSUE THREAD

**Issue by tricid** [l1j/en#466]
can consider this my pet project if no one else wants to do it, putting it here as a reminder though

log npcid, name, location (x,y,mapid), killer char name, that players bp (at that time), and datestamp

**Comment by smith-j-travis** [comment]
Boss kills are now logging as of #479.

However, I'm leaving this open as we still need to create something that lists rankings

**Comment by smith-j-travis** [comment]
#483 closes this
