### ISSUE TITLE
Pledge with space gives "too many recipients" error

### ISSUE THREAD

**Issue by smith-j-travis** [l1j/en#475]
Reported in IRC.. Need to look into it.

[22:14] <Jason_> I've recently made a BP and has a space in it
[22:14] <Jason_> when I try to send the BP a letter, it says there's too many recipients

**Comment by smith-j-travis** [comment]
Turns out we cannot allow spaces in bloodpledge names. Gonna write something up that will

1) Update the DB to remove spaces in all BP names
2) Remove spaces in the BP name on creation
3) Just in case, I will remove spaces when calling getclanname on an L1PcInstance and L1Clan just to be safe

**Comment by somekoreanguy** [comment]
Sound good~! Thanks ^^

**Comment by smith-j-travis** [comment]
Closed in #478
