### ISSUE TITLE
Player botting

### ISSUE THREAD

**Issue by s137948620** [l1j/en#487]
Player ID: Neon is confirmed botting in Forest of Mirror today

He uses auto teleport, auto haste and wafer, and auto attack

Many players in game has also confirmed.

Please investigate

**Comment by smith-j-travis** [comment]
Yeah we've already gotten a report in game but he hasn't been on while I've been on.

Closing this as github is really meant for issues with the source code and not reporting botters. Reporting them is best done via the forums or -bug ingame.
