### ISSUE TITLE
pots price charge wrong

### ISSUE THREAD

**Issue by s137948620** [l1j/en#494]
Hi,

I found out the charge for the pots is wrong today. I bought 500 a-clear, but it only charged me like couple thousands adena. I tested with other pots in other shops too, seems all have the same problem.

the problem seems to happen just starting today. 

I just found out that the charges for other stuff are wrong too.

Please investigate.

Thanks,

**Comment by smith-j-travis** [comment]
Removing the commit we think broke it. so I'm gonna close this.

Thanks for the report!
