### ISSUE TITLE
shock stun

### ISSUE THREAD

**Issue by tricid** [l1j/en#62]
currently hard set to 2s without any calculations for length of stun.

**Comment by Soren8** [comment]
Duration was always random on live, and having random chance AND duration based on level makes lower level knights essentially useless - which is kind of outside of the theme of Lin fights IMO. Lower level players were always of limited usefulness in fights on live, which I think is a defining part of the game.

**Comment by tricid** [comment]
I strongly disagree.  Live _like_, not exact, has always been the goal.  This allowed us to not nerf stun success chances across the board (to keep low level knights from having too much power) while making the stun stronger as the levels got higher, and it still kept it random, just weighted.  It was done on linret because knights were becoming rarely played.  This somewhat buffed stuns without making low level knights too disruptive.   I'm still unsure why it had a 6sec cap though, that's excessive.
