### ISSUE TITLE
Force quit logs you off no matter what

### ISSUE THREAD

**Issue by ZyreWK** [l1j/en#73]
By alt+tabbing you can force quit even though mobs are hitting you, you're e-binded or whatever.

**Comment by smith-j-travis** [comment]
Fixed by pull request #357.

Logic is as follows: 

- if you do an aggressive act to someone outside of a safety zone (attack, skill, spell), you get a timer set that holds you in game
- Walking or teleporting into a safety zone resets the counter
- When in a safety zone, the counter remains at 0
